[package]
name = "hashgoblin"
version = "0.1.0"
edition = "2021"

[dependencies]
digest = "0.10.7"
gumdrop = "0.8.1"
hex = "0.4.3"
jiff = "0.2.1"
md-5 = "0.10.6"
sha1 = "0.10.6"
sha2 = "0.10.8"
tiger = "0.2.1"
whirlpool = "0.10.4"
